# Generated by Django 6.1.1 on 2026-10-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_myself', models.TextField()),
                ('education', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=255)),
                ('my_stack', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.TextField()),
                ('main_description', models.TextField()),
                ('portfolio_img', models.ImageField(upload_to='portfolio')),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_of')),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.aboutme')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
