# Generated by Django 6.1.1 on 2026-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=280)),
                ('project_screen_shot', models.ImageField(upload_to='project')),
                ('github_link', models.CharField(max_length=400)),
            ],
        ),
    ]
